# -*- coding: utf-8 -*-
"""alpha_version_notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169QqsfCcGUdHqy_AwOerpRm2zXCTCeWB
"""


#  MODIFICACIÓ / MILLORES CODI GIFS


from tensorflow.keras.layers import Conv2D, UpSampling2D, Input
from tensorflow.keras.models import Model
from skimage.transform import resize
from skimage.color import rgb2lab, lab2rgb
from skimage.io import imread, imsave
from skimage import color, transform
from PIL import Image
import numpy as np
import imageio
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.animation import ArtistAnimation



# Función para aplicar el proceso de coloración a un cuadro
def colorize_frame(frame):
    # Preprocesar el cuadro de imagen (por ejemplo, convertir RGB a LAB)
    gray_frame = rgb2lab(frame)[:, :, 0]
    gray_frame = resize(gray_frame, (400, 400))
    X = gray_frame.reshape(1, 400, 400, 1)

    # Apilar el cuadro en una entrada de 3 canales (RGB)
    # X = np.repeat(X, 3, axis=2)

    # Obtener la predicción del modelo para el cuadro
    output = model.predict(X)
    output *= 128

    # Generar la imagen final en color
    colored_frame = np.zeros((400, 400, 3))
    colored_frame[:, :, 0] = X[:, :, 0]
    colored_frame[:, :, 1:] = output[0]

    # Convertir la imagen de LAB a RGB
    colored_frame = lab2rgb(colored_frame)
    colored_frame = (colored_frame * 255).astype(np.uint8)

    return colored_frame


# Building the neural network
input_shape = (400, 400, 1)
inputs = Input(shape=input_shape)

x = Conv2D(8, (3, 3), activation='relu', padding='same')(inputs)
x = Conv2D(8, (3, 3), activation='relu', padding='same', strides=2)(x)
x = Conv2D(16, (3, 3), activation='relu', padding='same')(x)
x = Conv2D(16, (3, 3), activation='relu', padding='same', strides=2)(x)
x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = Conv2D(32, (3, 3), activation='relu', padding='same', strides=2)(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same', strides=2)(x)

x = UpSampling2D((2, 2))(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(32, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(16, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
outputs = Conv2D(8, (3, 3), activation='tanh', padding='same')(x)

model = Model(inputs=inputs, outputs=outputs)


# Abrir el archivo GIF
gif = Image.open('Vho.gif')
frames = []

for frame in range(gif.n_frames):
    # Obtener el cuadro actual
    gif.seek(frame)
    frame_image = gif.copy()

    # Convertir el cuadro a RGB si es necesario
    if frame_image.mode != 'RGB':
        frame_image = frame_image.convert('RGB')

    # Ajustar el tamaño del cuadro original si es necesario
    if frame_image.size != (400, 400):
        frame_image = frame_image.resize((400, 400), Image.BILINEAR)

    # Aplicar la coloración al cuadro actual
    colored_frame = colorize_frame(np.array(frame_image))

    # Agregar el cuadro coloreado a la lista de cuadros
    frames.append(colored_frame)


# Crear la figura y el eje
fig, ax = plt.subplots()
ax.axis('off')

# Crear una lista de artistas para la animación
artists = []
for frame in frames:
    artist = [ax.imshow(frame)]
    artists.append(artist)

# Crear la animación
ani = ArtistAnimation(fig, artists, interval=gif.info['duration'], blit=True)

# Guardar los cuadros generados 
imageio.mimsave('Vho_02.gif', frames)

# Abrir y mostrar el GIF guardado
saved_gif = Image.open('Vho_02.gif')

# Abrir y mostrar el GIF guardado utilizando plt.imshow()
plt.imshow(saved_gif)
plt.axis('off')
plt.show()